### ISSUE TITLE
Option to create content with placeholders instead of entering info during build

### ISSUE THREAD

**Issue by a2sheppy** [jpmedley/mdn-helper#5]
Currently, the build command asks questions as it works on generating HTML for a term, such as asking for a description, asking for the syntax, and so forth.

It would be nice if, instead of asking all those questions and filling out that information, the build command could be told to simply put placeholders into the HTML for filling out by the user afterward. They would be easier to edit and style using a proper editor. An option for this would be helpful.

As an aside: it would be interesting to investigate formatting the placeholders such as to allow them to work with CKEditor's placeholder functionality, where it presents the placeholders formatted specially and lets you click and fill them out almost form-like.

**Comment by jpmedley** [comment]
What is the placeholder used by the CKEditor?

**Comment by a2sheppy** [comment]
CKEditor's Placeholders plugin: https://ckeditor.com/cke4/addon/placeholder

**Comment by jpmedley** [comment]
With [this commit](https://github.com/jpmedley/mdn-helper/commit/77c77a929113789852c54757fc13176d07490d8a) helper dumps templates to files without prompting for questions. Placeholders still need to be added

**Comment by jpmedley** [comment]
The current default is to dump the created files. The `-i` flag makes the process interactive as previously.
